language: python
python:
- "3.6"
- "3.7"
dist: xenial
install:
- pip install fs sqlalchemy pytest python-coveralls coverage pylint
script:
- pylint src/sqliteupload
- coverage run --source . -m pytest
- coverage report --omit */Lib/*,tests/*
- coverage html --omit */Lib/*,tests/*
after_success:
- coveralls
